from sqlalchemy import *
from config import host, port, database, user, password

conn_str = f"postgresql://{user}:{password}@{host}/{database}"
engine = create_engine(conn_str)
connection = engine.connect()
metadata = MetaData()
cheesy_tb = Table('cheesy_shit', metadata,
    Column('index', Integer, nullable=False),
    Column('insta_url', String(255), nullable=False),
    Column('caption', String(255), nullable=False)
)

metadata.create_all(engine)

query = insert(cheesy_tb).values(index=1, insta_url="""https://www.instagram.com/p/CPys1h1ttkp/?utm_source=ig_web_copy_link""", caption="""I may be broke, but I'll nvr break your heart""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=2, insta_url="""https://www.instagram.com/p/CPMoFGglXMN/?utm_source=ig_web_copy_link""", caption="""any meal with you is a Happy Meal""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=3, insta_url="""https://www.instagram.com/p/CPivt4jtIt0/?utm_source=ig_web_button_share_sheet""", caption="""while I'll like to date this gal @Upsydownsy""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=4, insta_url="""https://www.instagram.com/p/CPL0qQztjYn/?utm_source=ig_web_copy_link""", caption="""they didn't know the fastest thing is actually my heart rate when I'm arnd you""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=5, insta_url="""https://www.instagram.com/p/CPxOapnLYhQ/?utm_source=ig_web_copy_link""", caption="""that is, until I see your dp everyday""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=6, insta_url="""https://www.instagram.com/p/CPy6TiErQKV/?utm_source=ig_web_copy_link""", caption="""the true horror is seeing a future that doesn't involve you""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=7, insta_url="""https://www.instagram.com/p/CPyqT_vBejj/?utm_source=ig_web_copy_link""", caption="""while I'm hoping to take the sing-le out of sing-yi""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=8, insta_url="""https://www.instagram.com/p/CPguzmeIWNw/?utm_source=ig_web_copy_link""", caption="""the only thing I could catch are feelings for you""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=9, insta_url="""https://www.instagram.com/p/CPzL2r6I6TQ/?utm_source=ig_web_copy_link""", caption="""how could I breathe when u constantly take my breath away""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=10, insta_url="""https://www.instagram.com/p/CPwtOg8tZgE/?utm_source=ig_web_copy_link""", caption="""are you the moon? because even when in the darkest moments you still seem to shine""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=11, insta_url="""https://www.instagram.com/p/CPyaSpLBbwu/?utm_source=ig_web_copy_link""", caption="""but falling for you was no accident""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=12, insta_url="""https://www.instagram.com/p/CPwoCVWDAgR/?utm_source=ig_web_copy_link""", caption="""idk what you would want to hear, but I know I just want to hear your voice again""")
connection = engine.connect()
ResultProxy = connection.execute(query)
query = insert(cheesy_tb).values(index=13, insta_url="""https://www.instagram.com/p/CPwaAMyHfU3/?utm_source=ig_web_copy_link""", caption="""cos I wanna see you every morning""")
connection = engine.connect()
ResultProxy = connection.execute(query)
